//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace animalWeightTracker_00183727
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public daily_log()
        {
            this.daily_exercise = new HashSet<daily_exercise>();
            this.daily_measurement = new HashSet<daily_measurement>();
            this.daily_meal = new HashSet<daily_meal>();
        }
    
        public int log_Id { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> activity_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string progress { get; set; }
    
        public virtual activity activity { get; set; }
        public virtual course course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<daily_exercise> daily_exercise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<daily_measurement> daily_measurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<daily_meal> daily_meal { get; set; }
    }
}
