//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace animalWeightTracker_00183727
{
    using System;
    using System.Collections.Generic;

    public abstract class Person {
       
        public string name { get; set; }
        public string age { get; set; }
    }

    public partial class staff:Person
    {
  
        public staff()
        {
            this.courses = new HashSet<course>();
        }

        public int staff_Id { get; set; }
        public string deg { get; set; }
        public Nullable<int> org_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course> courses { get; set; }
        public virtual organization organization { get; set; }
    }
}
